# Generated by Django 3.0.8 on 2020-07-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
