# Generated by Django 3.0.8 on 2020-07-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20200721_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='done',
            field=models.BooleanField(null=True),
        ),
    ]
