# Generated by Django 3.0.8 on 2020-07-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20200721_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='done',
        ),
        migrations.AddField(
            model_name='case',
            name='finished',
            field=models.CharField(default='On going', max_length=50),
        ),
    ]
